defaults: &default
  adaptive_tweets_endpoint: 'http://adaptive-test-api.herokuapp.com/tweets.json'
  coke_keywords:
    - 'coke'
    - 'diet cola'
    - 'coca-cola'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default