development:
  adapter: postgresql
  database: adaptive_labs_code_test_development
  user: postgres
  password:
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: adaptive_labs_code_test_test
  user: postgres
  password:
  pool: 5
  timeout: 5000